# Generated by Django 3.2.9 on 2022-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_relative_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='relative',
        ),
    ]
